<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Willkommen bei Blue Liquids'), '<span class="zf-green">', '</span>') ?></h1>
    <p>
        Das ist einfach eine kleine Seite auf denen man seine Bestellungen abgeben kann und sich die aktuell verfügbaren Aromen ansehen kann.
        Man kann auch neue Aromen bestellen, wenn die aktuelle Auswahl nicht zusagen sollte :)
    </p>
</div>
